version: "3.9"

services:
  database:
    platform: linux/x86_64
    image: 'postgres:latest'
    container_name: paymentDB
    ports:
      - '5435:5432'
    volumes:
      - ./:/app/
    environment:
      POSTGRES_DB: paymentDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - internal

  app:
    container_name: paymentService
    command: java -jar target/PaymentService-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8083:8083'
    depends_on:
      - database
    volumes:
      - ./:/app/app
    links:
      - database
    networks:
      - internal
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/paymentDB
      - spring_rabbitmq_host=host.docker.internal
      - spring_rabbitmq_port=5672

networks:
  internal:
    name: internal